--------------------------------------------------------
--  Fichier créé - mardi-janvier-05-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."RESERVATION";
DROP TABLE "SYSTEM"."FICHES";
DROP TABLE "SYSTEM"."INVITE";
DROP TABLE "SYSTEM"."RECEPTION";
DROP TABLE "SYSTEM"."EMPLOYES";
DROP TABLE "SYSTEM"."COLLABORATEURS";
DROP TABLE "SYSTEM"."CLIENT";
DROP TABLE "SYSTEM"."CATEGORIEES";
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RESERVATION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"GP_MUSIC" VARCHAR2(20 BYTE), 
	"GP_SERVEUR" VARCHAR2(20 BYTE), 
	"GP_DECO" VARCHAR2(20 BYTE), 
	"GP_PATISERIE" VARCHAR2(20 BYTE), 
	"GP_PHOTOGRAPHIE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FICHES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FICHES" 
   (	"RES" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"DATEE" VARCHAR2(20 BYTE), 
	"NBA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVITE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."INVITE" 
   (	"ID_INV" VARCHAR2(20 BYTE), 
	"NOMBRE_DE_PLACES_RESERVES" VARCHAR2(20 BYTE), 
	"NUMERO_TABLE" VARCHAR2(20 BYTE), 
	"MAIL_INVITE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECEPTION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECEPTION" 
   (	"ID_RECEP" VARCHAR2(20 BYTE), 
	"VILLE_RECEP" VARCHAR2(20 BYTE), 
	"SALLE_RESERVEE" VARCHAR2(20 BYTE), 
	"NOMBRE_DES_INVITES" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATEN" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLLABORATEURS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COLLABORATEURS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"BUDGET_MAX" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"D_MARAIGE" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIEES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CATEGORIEES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DATE_DC" VARCHAR2(20 BYTE), 
	"DATE_FC" VARCHAR2(20 BYTE), 
	"DOMAINE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.RESERVATION
SET DEFINE OFF;
Insert into SYSTEM.RESERVATION (ID,GP_MUSIC,GP_SERVEUR,GP_DECO,GP_PATISERIE,GP_PHOTOGRAPHIE) values ('123145','ZER','TERTYTYU','TYU','TYU','TY');
REM INSERTING into SYSTEM.FICHES
SET DEFINE OFF;
REM INSERTING into SYSTEM.INVITE
SET DEFINE OFF;
Insert into SYSTEM.INVITE (ID_INV,NOMBRE_DE_PLACES_RESERVES,NUMERO_TABLE,MAIL_INVITE) values ('12','2','5','mama');
REM INSERTING into SYSTEM.RECEPTION
SET DEFINE OFF;
REM INSERTING into SYSTEM.EMPLOYES
SET DEFINE OFF;
REM INSERTING into SYSTEM.COLLABORATEURS
SET DEFINE OFF;
Insert into SYSTEM.COLLABORATEURS (ID,MARQUE,ADRESSE,MAIL,NUMERO) values ('1234','ARARAR',null,null,'0');
Insert into SYSTEM.COLLABORATEURS (ID,MARQUE,ADRESSE,MAIL,NUMERO) values ('0',null,null,null,'0');
Insert into SYSTEM.COLLABORATEURS (ID,MARQUE,ADRESSE,MAIL,NUMERO) values ('12333','MOATAZ','AA','ATATA','0');
REM INSERTING into SYSTEM.CLIENT
SET DEFINE OFF;
Insert into SYSTEM.CLIENT (ID,NOM,PRENOM,BUDGET_MAX,NUMERO,D_MARAIGE,CATEGORIE) values ('654321','AHMED','DGAG','200','53899000','09/00/2000','Mariage Modern');
Insert into SYSTEM.CLIENT (ID,NOM,PRENOM,BUDGET_MAX,NUMERO,D_MARAIGE,CATEGORIE) values ('132426','ZER','ERT','ERTYUIOP','52535666','11/11/1111','Mariage Modern');
Insert into SYSTEM.CLIENT (ID,NOM,PRENOM,BUDGET_MAX,NUMERO,D_MARAIGE,CATEGORIE) values ('123999','ZERT','ZERT','ZERT','55555555','11/11/1111','Mariage Traditionnel');
REM INSERTING into SYSTEM.CATEGORIEES
SET DEFINE OFF;
Insert into SYSTEM.CATEGORIEES (ID,DATE_DC,DATE_FC,DOMAINE) values ('12349','ERTY','ERTY','TY');
Insert into SYSTEM.CATEGORIEES (ID,DATE_DC,DATE_FC,DOMAINE) values ('12345','11','11','11');
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RESERVATION_PK" ON "SYSTEM"."RESERVATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FICHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FICHES_PK" ON "SYSTEM"."FICHES" ("RES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INVITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INVITE_PK" ON "SYSTEM"."INVITE" ("ID_INV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECEPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RECEPTION_PK" ON "SYSTEM"."RECEPTION" ("ID_RECEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYES_PK" ON "SYSTEM"."EMPLOYES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COLLABORATEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COLLABORATEURS_PK" ON "SYSTEM"."COLLABORATEURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENT_PK" ON "SYSTEM"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORIEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CATEGORIEES_PK" ON "SYSTEM"."CATEGORIEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FICHES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FICHES" ADD CONSTRAINT "FICHES_PK" PRIMARY KEY ("RES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FICHES" MODIFY ("RES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."INVITE" ADD CONSTRAINT "INVITE_PK" PRIMARY KEY ("ID_INV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."INVITE" MODIFY ("ID_INV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPTION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECEPTION" ADD CONSTRAINT "RECEPTION_PK" PRIMARY KEY ("ID_RECEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RECEPTION" MODIFY ("ID_RECEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLABORATEURS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COLLABORATEURS" ADD CONSTRAINT "COLLABORATEURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."COLLABORATEURS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIEES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CATEGORIEES" ADD CONSTRAINT "CATEGORIEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CATEGORIEES" MODIFY ("ID" NOT NULL ENABLE);
